export const ERROR_CODES = [
  'CF_UNREACHABLE', 'CF_TOKEN_INVALID', 'CF_PERMISSION_MISSING', 'CF_RATE_LIMITED', 'CF_API_ERROR',
  'CF_NOT_CONNECTED', 'ACCOUNT_SELECTION_REQUIRED', 'DNS_CONFLICT', 'DNS_RECORD_NOT_FOUND', 'ZONE_NOT_FOUND',
  'CONFIG_VERSION_CONFLICT', 'TUNNEL_NOT_FOUND', 'TUNNEL_NOT_MANAGED', 'TUNNEL_NOT_REMOTE',
  'SERVICE_COMMAND_FAILED', 'VALIDATION_ERROR', 'UNAUTHORIZED', 'SETUP_ALREADY_DONE',
  'INVALID_CREDENTIALS', 'RATE_LIMITED', 'CLOUDFLARED_UPDATE_UNSUPPORTED', 'INTERNAL',
] as const;
export type ErrorCode = (typeof ERROR_CODES)[number];
export interface ApiErrorBody { code: ErrorCode; message: string; details?: unknown }
